### ISSUE TITLE
MTLTextureUsageShaderWrite error iOS 9.1 and later

### ISSUE THREAD

**Issue by racewalkWill** [rhoeper/Filterpedia-Swift4#1]
ISSUE: Metal Functions have an error message 'Error validateComputeFunctionArguments:892: failed assertion `Compute Function(ciKernelMain): writes texture ([0]) whose usage (0x01) doesn't specify MTLTextureUsageShaderWrite (0x02)'

FIX: Per apple developer forum thread https://forums.developer.apple.com/thread/23795 the MTLTextureDescriptor now needs the usage value set as in  

textureDescriptor!.usage = MTLTextureUsage.shaderRead.

Further a new textureDescriptor object is needed for the kernelOutputTexture with value set to MTLTextureUsage.shaderWrite.
I'm not quite sure how to branch on some else's repo so the code fix is below.

regards
Will L-B

fix below
 func imageFromComputeShader(width: CGFloat, height: CGFloat, inputImage: CIImage?) -> CIImage
    {
        if textureDescriptor == nil
        {
            textureDescriptor = MTLTextureDescriptor.texture2DDescriptor(pixelFormat: .rgba8Unorm,
                width: Int(width),
                height: Int(height),
                mipmapped: false)

            textureDescriptor!.usage =[MTLTextureUsage.shaderRead,MTLTextureUsage.shaderWrite] //  fixes error in iOS9.1
            kernelInputTexture = device.makeTexture(descriptor: textureDescriptor!)

// new textureDescriptor for the kernelOutputTexture
            textureDescriptorOut = MTLTextureDescriptor.texture2DDescriptor(pixelFormat: .rgba8Unorm,
                                                                         width: Int(width),
                                                                         height: Int(height),
                                                                         mipmapped: false)

            textureDescriptorOut!.usage = [MTLTextureUsage.shaderWrite, MTLTextureUsage.shaderRead ]
            kernelOutputTexture = device.makeTexture(descriptor: textureDescriptorOut!)
            // END fixes error in iOS9.1

            threadgroupsPerGrid = MTLSizeMake(
                textureDescriptor!.width / threadsPerThreadgroup.width,
                textureDescriptor!.height / threadsPerThreadgroup.height, 1)
        }

**Comment by rhoeper** [comment]
Thanks, Will L-B,

I’ll look into this later this week when my time opens up.

Meanwhile, the reason I cloned Filterpedia and reposted it was twofold: 1. I needed to experiment locally with filtering, and 2. I’m not entirely familiar with how GitHub works with all the changes I had to make to bring the cloned version forward.  Simon gave his approval for my assistance as he can no longer support his open-source work while he is employed by Apple. I have no problem with you forking the current version, if that’s possible, and I’m pretty sure Simon would say the same.

Thanks for the update, I haven’t compiled it since last year prior to OS 12 and Xcode 10 and was not receiving errors at that time.

Richard Hoeper

**Comment by racewalkWill** [comment]
Hi Richard,
I’m just getting the hang of a GitHub process. .. I have forked the repository and created a pull request with the change. The changes in the MetalFilters.swift are on the forked version.
This page on git hub helped… https://help.github.com/en/articles/about-pull-requests <https://help.github.com/en/articles/about-pull-requests>

It looks like the change can merge into the master version with the push of a button.

There are a few other custom filters not working due to parm type issues. I may be able to get those fixed too (have to see how my own work goes).

BTW - the app has been very helpful in learning the ropes of CIFilter/CIImage. Thanks to both you and Simon, it’s much appreciated!

Will 

p.s. the typing errors.. I’ll look at these too
Filterpedia.BayerDitherFilter.
[CIKernelPool] 3:43: ERROR: parameter has unexpected type 'vec4' (should be a sampler type)
   int columnIndex = int(mod(samplerCoord(image).x / pixelWidth, 3.0)); 
                                          ^
[CIKernelPool] 4:40: ERROR: parameter has unexpected type 'vec4' (should be a sampler type)
   int rowIndex = int(mod(samplerCoord(image).y, pixelHeight)); 
                                       ^
2 errors generated.
2019-03-04 10:12:10.040576-0600 Filterpedia[7990:1194297] [compile] [CIColorKernel initWithString:] failed due to error parsing kernel source.


On Mar 4, 2019, at 6:49 AM, Richard <notifications@github.com> wrote:

Thanks, Will L-B,

I’ll look into this later this week when my time opens up.

Meanwhile, the reason I cloned Filterpedia and reposted it was twofold: 1. I needed to experiment locally with filtering, and 2. I’m not entirely familiar with how GitHub works with all the changes I had to make to bring the cloned version forward. Simon gave his approval for my assistance as he can no longer support his open-source work while he is employed by Apple. I have no problem with you forking the current version, if that’s possible, and I’m pretty sure Simon would say the same.

Thanks for the update, I haven’t compiled it since last year prior to OS 12 and Xcode 10 and was not receiving errors at that time.

Richard Hoeper

**Comment by rhoeper** [comment]
Hi,

I fixed recent issues in my drawing app (which uses about 40 filters) having to do with “unexpected type 'vec4' (should be a sampler type)”

This is before from 5/18/2018
class SmoothThreshold: CIFilter
{
    @objc var inputImage : CIImage?
    @objc var inputEdgeO: CGFloat = 0.25
    @objc var inputEdge1: CGFloat = 0.75
    
    override var attributes: [String : Any]
    {
        return [
            kCIAttributeFilterDisplayName: "B/W Smooth Threshold" as AnyObject,
            "inputImage": [kCIAttributeIdentity: 0,
                           kCIAttributeClass: "CIImage",
                           kCIAttributeDisplayName: "Image",
                           kCIAttributeType: kCIAttributeTypeImage],
            "inputEdgeO": [kCIAttributeIdentity: 0,
                           kCIAttributeClass: "NSNumber",
                           kCIAttributeDefault: 0.25,
                           kCIAttributeDisplayName: "Edge 0",
                           kCIAttributeMin: 0.0,
                           kCIAttributeSliderMin: 0.0,
                           kCIAttributeSliderMax: 1.0,
                           kCIAttributeType: kCIAttributeTypeScalar],
            "inputEdge1": [kCIAttributeIdentity: 0,
                           kCIAttributeClass: "NSNumber",
                           kCIAttributeDefault: 0.75,
                           kCIAttributeDisplayName: "Edge 1",
                           kCIAttributeMin: 0.0,
                           kCIAttributeSliderMin: 0.0,
                           kCIAttributeSliderMax: 1.0,
                           kCIAttributeType: kCIAttributeTypeScalar]
        ]
    }
    
    let colorKernel = CIColorKernel(source:
        "kernel vec4 color(__sample pixel, float inputEdgeO, float inputEdge1)" +
            "{" +
            "   float pixalpha;" +
            "   pixalpha = sample(pixel, samplerCoord(pixel)).a;" +
            "    float luma = dot(pixel.rgb, vec3(0.2126, 0.7152, 0.0722));" +
            "    float threshold = smoothstep(inputEdgeO, inputEdge1, luma);" +
            "    return vec4(threshold, threshold, threshold, pixalpha);" +
        "}"
    )
    
    override var outputImage: CIImage!
    {
        guard let inputImage = inputImage,
            let colorKernel = colorKernel else
        {
            return nil
        }
        
        let extent = inputImage.extent
        let arguments = [inputImage,
                         min(inputEdgeO, inputEdge1),
                         max(inputEdgeO, inputEdge1),] as [Any]
        
        return colorKernel.apply(extent: extent, arguments: arguments)
    }
}
***********
This is the updated version from 1/21/19
class SmoothThreshold: CIFilter
{
    @objc var inputImage : CIImage?
    @objc var inputEdgeO: CGFloat = 0.25
    @objc var inputEdge1: CGFloat = 0.75
    
    override var attributes: [String : Any]
    {
        return [
            kCIAttributeFilterDisplayName: "B/W Smooth Threshold" as AnyObject,
            "inputImage": [kCIAttributeIdentity: 0,
                           kCIAttributeClass: "CIImage",
                           kCIAttributeDisplayName: "Image",
                           kCIAttributeType: kCIAttributeTypeImage],
            "inputEdgeO": [kCIAttributeIdentity: 0,
                           kCIAttributeClass: "NSNumber",
                           kCIAttributeDefault: 0.25,
                           kCIAttributeDisplayName: "Edge 0",
                           kCIAttributeMin: 0.0,
                           kCIAttributeSliderMin: 0.0,
                           kCIAttributeSliderMax: 1.0,
                           kCIAttributeType: kCIAttributeTypeScalar],
            "inputEdge1": [kCIAttributeIdentity: 0,
                           kCIAttributeClass: "NSNumber",
                           kCIAttributeDefault: 0.75,
                           kCIAttributeDisplayName: "Edge 1",
                           kCIAttributeMin: 0.0,
                           kCIAttributeSliderMin: 0.0,
                           kCIAttributeSliderMax: 1.0,
                           kCIAttributeType: kCIAttributeTypeScalar]
        ]
    }
    
    let colorKernel = CIKernel(source:
        "kernel vec4 color(sampler pixel, float inputEdgeO, float inputEdge1)" +
            "{" +
            "   float pixalpha;" +
            "   pixalpha = sample(pixel, samplerCoord(pixel)).a;" +
            "    float luma = dot(sample(pixel, samplerCoord(pixel)).rgb, vec3(0.2126, 0.7152, 0.0722));" +
            "    float threshold = smoothstep(inputEdgeO, inputEdge1, luma);" +
            "    return vec4(threshold, threshold, threshold, pixalpha);" +
        "}"
    )
    
    override var outputImage: CIImage!
    {
        guard let inputImage = inputImage,
            let colorKernel = colorKernel else
        {
            return nil
        }
        
        let extent = inputImage.extent
        let arguments = [inputImage,
                         min(inputEdgeO, inputEdge1),
                         max(inputEdgeO, inputEdge1),] as [Any]
        
        return colorKernel.apply(extent: extent,
                                 roiCallback: {
                                    (index, rect) in
                                    return rect
                                 },
                                 arguments: arguments)
    }
}

I used a lot of pixalpha in the returns because with a layered drawing app, I need to maintain transparencies between the overlays. If I remember correctly, Simon mostly uses 1.0 as alpha.

I have no problem with you merging your forked changes back to the master.  Please make sure and give yourself credit for any changes, or I can update the text to note this.

Richard

**Comment by racewalkWill** [comment]
Hi Richard,
Github mysteries… you do the promote I guess - see https://help.github.com/en/articles/merging-a-pull-request <https://help.github.com/en/articles/merging-a-pull-request>

Appreciate your solution for the “unexpected type vec4’.. I found four filters that needed it or similar. That and the 3 metal filters makes seven filters total fixed.

It was a GOOD learning experience to do all of them.. almost like a class homework assignment. I learned a lot!

There is one filter error that I side stepped:   "Lens Correction for AVC”   CICameraCalibrationLensCorrection - 52 attributes.. (whoa nellie! Someone is playing with a full deck! ).

My files are on the fork 
racewalkWill <https://github.com/racewalkWill>/Filterpedia-Swift4 <https://github.com/racewalkWill/Filterpedia-Swift4>
forked from rhoeper/Filterpedia-Swift4 <https://github.com/rhoeper/Filterpedia-Swift4>

And in case all the GitHub is too much.. here is a zip of the five changed files..

Again thanks very much !
Will Loew-Blosser



On Mar 4, 2019, at 11:02 AM, Richard <notifications@github.com> wrote:

Hi,

I fixed recent issues in my drawing app (which uses about 40 filters) having to do with “unexpected type 'vec4' (should be a sampler type)”

This is before from 5/18/2018
class SmoothThreshold: CIFilter
{
@objc var inputImage : CIImage?
@objc var inputEdgeO: CGFloat = 0.25
@objc var inputEdge1: CGFloat = 0.75

override var attributes: [String : Any]
{
return [
kCIAttributeFilterDisplayName: "B/W Smooth Threshold" as AnyObject,
"inputImage": [kCIAttributeIdentity: 0,
kCIAttributeClass: "CIImage",
kCIAttributeDisplayName: "Image",
kCIAttributeType: kCIAttributeTypeImage],
"inputEdgeO": [kCIAttributeIdentity: 0,
kCIAttributeClass: "NSNumber",
kCIAttributeDefault: 0.25,
kCIAttributeDisplayName: "Edge 0",
kCIAttributeMin: 0.0,
kCIAttributeSliderMin: 0.0,
kCIAttributeSliderMax: 1.0,
kCIAttributeType: kCIAttributeTypeScalar],
"inputEdge1": [kCIAttributeIdentity: 0,
kCIAttributeClass: "NSNumber",
kCIAttributeDefault: 0.75,
kCIAttributeDisplayName: "Edge 1",
kCIAttributeMin: 0.0,
kCIAttributeSliderMin: 0.0,
kCIAttributeSliderMax: 1.0,
kCIAttributeType: kCIAttributeTypeScalar]
]
}

let colorKernel = CIColorKernel(source:
"kernel vec4 color(__sample pixel, float inputEdgeO, float inputEdge1)" +
"{" +
" float pixalpha;" +
" pixalpha = sample(pixel, samplerCoord(pixel)).a;" +
" float luma = dot(pixel.rgb, vec3(0.2126, 0.7152, 0.0722));" +
" float threshold = smoothstep(inputEdgeO, inputEdge1, luma);" +
" return vec4(threshold, threshold, threshold, pixalpha);" +
"}"
)

override var outputImage: CIImage!
{
guard let inputImage = inputImage,
let colorKernel = colorKernel else
{
return nil
}

let extent = inputImage.extent
let arguments = [inputImage,
min(inputEdgeO, inputEdge1),
max(inputEdgeO, inputEdge1),] as [Any]

return colorKernel.apply(extent: extent, arguments: arguments)
}
}
***********
This is the updated version from 1/21/19
class SmoothThreshold: CIFilter
{
@objc var inputImage : CIImage?
@objc var inputEdgeO: CGFloat = 0.25
@objc var inputEdge1: CGFloat = 0.75

override var attributes: [String : Any]
{
return [
kCIAttributeFilterDisplayName: "B/W Smooth Threshold" as AnyObject,
"inputImage": [kCIAttributeIdentity: 0,
kCIAttributeClass: "CIImage",
kCIAttributeDisplayName: "Image",
kCIAttributeType: kCIAttributeTypeImage],
"inputEdgeO": [kCIAttributeIdentity: 0,
kCIAttributeClass: "NSNumber",
kCIAttributeDefault: 0.25,
kCIAttributeDisplayName: "Edge 0",
kCIAttributeMin: 0.0,
kCIAttributeSliderMin: 0.0,
kCIAttributeSliderMax: 1.0,
kCIAttributeType: kCIAttributeTypeScalar],
"inputEdge1": [kCIAttributeIdentity: 0,
kCIAttributeClass: "NSNumber",
kCIAttributeDefault: 0.75,
kCIAttributeDisplayName: "Edge 1",
kCIAttributeMin: 0.0,
kCIAttributeSliderMin: 0.0,
kCIAttributeSliderMax: 1.0,
kCIAttributeType: kCIAttributeTypeScalar]
]
}

let colorKernel = CIKernel(source:
"kernel vec4 color(sampler pixel, float inputEdgeO, float inputEdge1)" +
"{" +
" float pixalpha;" +
" pixalpha = sample(pixel, samplerCoord(pixel)).a;" +
" float luma = dot(sample(pixel, samplerCoord(pixel)).rgb, vec3(0.2126, 0.7152, 0.0722));" +
" float threshold = smoothstep(inputEdgeO, inputEdge1, luma);" +
" return vec4(threshold, threshold, threshold, pixalpha);" +
"}"
)

override var outputImage: CIImage!
{
guard let inputImage = inputImage,
let colorKernel = colorKernel else
{
return nil
}

let extent = inputImage.extent
let arguments = [inputImage,
min(inputEdgeO, inputEdge1),
max(inputEdgeO, inputEdge1),] as [Any]

return colorKernel.apply(extent: extent,
roiCallback: {
(index, rect) in
return rect
},
arguments: arguments)
}
}

I used a lot of pixalpha in the returns because with a layered drawing app, I need to maintain transparencies between the overlays. If I remember correctly, Simon mostly uses 1.0 as alpha.

I have no problem with you merging your forked changes back to the master. Please make sure and give yourself credit for any changes, or I can update the text to note this.

Richard

**Comment by rhoeper** [comment]
HI Will,

My pleasure.

 Later this week I’ll add a credit note with links to your fork. As Apple moves away from supporting openGLES3 there will be a lot more developers trying to figure Metal out, myself included.

Thanks for your hard work, and the zip file. 

Richard
