### ISSUE TITLE
How to create Glitch effect?

### ISSUE THREAD

**Issue by PawanmSpaceo** [rhoeper/Filterpedia-Swift4#3]
How to create Glitch effect? 

Sorry this is not a bug but I need to apply this filter

Thanks

**Comment by rhoeper** [comment]
I wasn't aware of that one, but searching online I see several concept examples. The question is which glitch version appeals to you. You might try this: https://snorpey.github.io/jpg-glitch-electron/

**Comment by PawanmSpaceo** [comment]
Thanks @rhoeper for your support
